# SPDX-FileCopyrightText: The stageset-controller Authors
# SPDX-License-Identifier: 0BSD

version = 1
SPDX-PackageName = "stageset-controller"
SPDX-PackageSupplier = "Sebastian Hoß <seb@xn--ho-hia.de>"
SPDX-PackageDownloadLocation = "https://github.com/metio/stageset-controller"

[[annotations]]
path = ["go.mod", "go.sum", ".gitignore", ".gitmodules", "renovate.json", "docs/**", "config/**", "LICENSES/**", "dev/website", "dev/serve", "skills/**", ".claude-plugin/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The stageset-controller Authors"
SPDX-License-Identifier = "0BSD"
