//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: The stageset-controller Authors
// SPDX-License-Identifier: 0BSD

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/fluxcd/pkg/apis/kustomize"
	"github.com/fluxcd/pkg/apis/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(int32)
		**out = **in
	}
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = new(PatchAction)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(WaitAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(JobAction)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(DeleteAction)
		**out = **in
	}
	if in.Apply != nil {
		in, out := &in.Apply, &out.Apply
		*out = new(ApplyAction)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisCheck) DeepCopyInto(out *AnalysisCheck) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Threshold.DeepCopyInto(&out.Threshold)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisCheck.
func (in *AnalysisCheck) DeepCopy() *AnalysisCheck {
	if in == nil {
		return nil
	}
	out := new(AnalysisCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisCheckResult) DeepCopyInto(out *AnalysisCheckResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisCheckResult.
func (in *AnalysisCheckResult) DeepCopy() *AnalysisCheckResult {
	if in == nil {
		return nil
	}
	out := new(AnalysisCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisResult) DeepCopyInto(out *AnalysisResult) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]AnalysisCheckResult, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisResult.
func (in *AnalysisResult) DeepCopy() *AnalysisResult {
	if in == nil {
		return nil
	}
	out := new(AnalysisResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyAction) DeepCopyInto(out *ApplyAction) {
	*out = *in
	out.SourceRef = in.SourceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyAction.
func (in *ApplyAction) DeepCopy() *ApplyAction {
	if in == nil {
		return nil
	}
	out := new(ApplyAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactVersionRef) DeepCopyInto(out *ArtifactVersionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactVersionRef.
func (in *ArtifactVersionRef) DeepCopy() *ArtifactVersionRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactVersionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetFreeze) DeepCopyInto(out *BudgetFreeze) {
	*out = *in
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetFreeze.
func (in *BudgetFreeze) DeepCopy() *BudgetFreeze {
	if in == nil {
		return nil
	}
	out := new(BudgetFreeze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConflictPolicy) DeepCopyInto(out *ConflictPolicy) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ConflictRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConflictPolicy.
func (in *ConflictPolicy) DeepCopy() *ConflictPolicy {
	if in == nil {
		return nil
	}
	out := new(ConflictPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConflictRule) DeepCopyInto(out *ConflictRule) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConflictRule.
func (in *ConflictRule) DeepCopy() *ConflictRule {
	if in == nil {
		return nil
	}
	out := new(ConflictRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConflictTarget) DeepCopyInto(out *ConflictTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConflictTarget.
func (in *ConflictTarget) DeepCopy() *ConflictTarget {
	if in == nil {
		return nil
	}
	out := new(ConflictTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHealthCheck) DeepCopyInto(out *CustomHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHealthCheck.
func (in *CustomHealthCheck) DeepCopy() *CustomHealthCheck {
	if in == nil {
		return nil
	}
	out := new(CustomHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decryption) DeepCopyInto(out *Decryption) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decryption.
func (in *Decryption) DeepCopy() *Decryption {
	if in == nil {
		return nil
	}
	out := new(Decryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteAction) DeepCopyInto(out *DeleteAction) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteAction.
func (in *DeleteAction) DeepCopy() *DeleteAction {
	if in == nil {
		return nil
	}
	out := new(DeleteAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorBudget) DeepCopyInto(out *ErrorBudget) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorBudget.
func (in *ErrorBudget) DeepCopy() *ErrorBudget {
	if in == nil {
		return nil
	}
	out := new(ErrorBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventCheck) DeepCopyInto(out *EventCheck) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventCheck.
func (in *EventCheck) DeepCopy() *EventCheck {
	if in == nil {
		return nil
	}
	out := new(EventCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventGate) DeepCopyInto(out *EventGate) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]EventCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventGate.
func (in *EventGate) DeepCopy() *EventGate {
	if in == nil {
		return nil
	}
	out := new(EventGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FastTrack) DeepCopyInto(out *FastTrack) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.After != nil {
		in, out := &in.After, &out.After
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FastTrack.
func (in *FastTrack) DeepCopy() *FastTrack {
	if in == nil {
		return nil
	}
	out := new(FastTrack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAction) DeepCopyInto(out *HTTPAction) {
	*out = *in
	if in.BodyFrom != nil {
		in, out := &in.BodyFrom, &out.BodyFrom
		*out = new(meta.SecretKeyReference)
		**out = **in
	}
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make([]meta.SecretKeyReference, len(*in))
		copy(*out, *in)
	}
	if in.ExpectedStatus != nil {
		in, out := &in.ExpectedStatus, &out.ExpectedStatus
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAction.
func (in *HTTPAction) DeepCopy() *HTTPAction {
	if in == nil {
		return nil
	}
	out := new(HTTPAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryEntry) DeepCopyInto(out *InventoryEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryEntry.
func (in *InventoryEntry) DeepCopy() *InventoryEntry {
	if in == nil {
		return nil
	}
	out := new(InventoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobAction) DeepCopyInto(out *JobAction) {
	*out = *in
	out.SourceRef = in.SourceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobAction.
func (in *JobAction) DeepCopy() *JobAction {
	if in == nil {
		return nil
	}
	out := new(JobAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSource) DeepCopyInto(out *MetricSource) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSource.
func (in *MetricSource) DeepCopy() *MetricSource {
	if in == nil {
		return nil
	}
	out := new(MetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Migration) DeepCopyInto(out *Migration) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Migration.
func (in *Migration) DeepCopy() *Migration {
	if in == nil {
		return nil
	}
	out := new(Migration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationsSource) DeepCopyInto(out *MigrationsSource) {
	*out = *in
	out.SourceRef = in.SourceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationsSource.
func (in *MigrationsSource) DeepCopy() *MigrationsSource {
	if in == nil {
		return nil
	}
	out := new(MigrationsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectVersionRef) DeepCopyInto(out *ObjectVersionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectVersionRef.
func (in *ObjectVersionRef) DeepCopy() *ObjectVersionRef {
	if in == nil {
		return nil
	}
	out := new(ObjectVersionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchAction) DeepCopyInto(out *PatchAction) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchAction.
func (in *PatchAction) DeepCopy() *PatchAction {
	if in == nil {
		return nil
	}
	out := new(PatchAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchTarget) DeepCopyInto(out *PatchTarget) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchTarget.
func (in *PatchTarget) DeepCopy() *PatchTarget {
	if in == nil {
		return nil
	}
	out := new(PatchTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingMigration) DeepCopyInto(out *PendingMigration) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingMigration.
func (in *PendingMigration) DeepCopy() *PendingMigration {
	if in == nil {
		return nil
	}
	out := new(PendingMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingUpdate) DeepCopyInto(out *PendingUpdate) {
	*out = *in
	if in.Revisions != nil {
		in, out := &in.Revisions, &out.Revisions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NextWindowOpens != nil {
		in, out := &in.NextWindowOpens, &out.NextWindowOpens
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingUpdate.
func (in *PendingUpdate) DeepCopy() *PendingUpdate {
	if in == nil {
		return nil
	}
	out := new(PendingUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostBuild) DeepCopyInto(out *PostBuild) {
	*out = *in
	if in.Substitute != nil {
		in, out := &in.Substitute, &out.Substitute
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SubstituteFrom != nil {
		in, out := &in.SubstituteFrom, &out.SubstituteFrom
		*out = make([]SubstituteReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostBuild.
func (in *PostBuild) DeepCopy() *PostBuild {
	if in == nil {
		return nil
	}
	out := new(PostBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusSource) DeepCopyInto(out *PrometheusSource) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusSource.
func (in *PrometheusSource) DeepCopy() *PrometheusSource {
	if in == nil {
		return nil
	}
	out := new(PrometheusSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionAnalysis) DeepCopyInto(out *PromotionAnalysis) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]AnalysisCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FailureLimit != nil {
		in, out := &in.FailureLimit, &out.FailureLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionAnalysis.
func (in *PromotionAnalysis) DeepCopy() *PromotionAnalysis {
	if in == nil {
		return nil
	}
	out := new(PromotionAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionState) DeepCopyInto(out *PromotionState) {
	*out = *in
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
	if in.SoakUntil != nil {
		in, out := &in.SoakUntil, &out.SoakUntil
		*out = (*in).DeepCopy()
	}
	if in.LastAnalysis != nil {
		in, out := &in.LastAnalysis, &out.LastAnalysis
		*out = new(AnalysisResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionState.
func (in *PromotionState) DeepCopy() *PromotionState {
	if in == nil {
		return nil
	}
	out := new(PromotionState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadyChecks) DeepCopyInto(out *ReadyChecks) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]meta.NamespacedObjectKindReference, len(*in))
		copy(*out, *in)
	}
	if in.Exprs != nil {
		in, out := &in.Exprs, &out.Exprs
		*out = make([]CustomHealthCheck, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadyChecks.
func (in *ReadyChecks) DeepCopy() *ReadyChecks {
	if in == nil {
		return nil
	}
	out := new(ReadyChecks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartCheck) DeepCopyInto(out *RestartCheck) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartCheck.
func (in *RestartCheck) DeepCopy() *RestartCheck {
	if in == nil {
		return nil
	}
	out := new(RestartCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartGate) DeepCopyInto(out *RestartGate) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]RestartCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartGate.
func (in *RestartGate) DeepCopy() *RestartGate {
	if in == nil {
		return nil
	}
	out := new(RestartGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceReference) DeepCopyInto(out *SourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceReference.
func (in *SourceReference) DeepCopy() *SourceReference {
	if in == nil {
		return nil
	}
	out := new(SourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stage) DeepCopyInto(out *Stage) {
	*out = *in
	out.SourceRef = in.SourceRef
	if in.Prune != nil {
		in, out := &in.Prune, &out.Prune
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ConflictPolicy != nil {
		in, out := &in.ConflictPolicy, &out.ConflictPolicy
		*out = new(ConflictPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyHelmHookResources != nil {
		in, out := &in.ApplyHelmHookResources, &out.ApplyHelmHookResources
		*out = new(bool)
		**out = **in
	}
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]kustomize.Patch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostBuild != nil {
		in, out := &in.PostBuild, &out.PostBuild
		*out = new(PostBuild)
		(*in).DeepCopyInto(*out)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = new(StageActions)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadyChecks != nil {
		in, out := &in.ReadyChecks, &out.ReadyChecks
		*out = new(ReadyChecks)
		(*in).DeepCopyInto(*out)
	}
	if in.Promotion != nil {
		in, out := &in.Promotion, &out.Promotion
		*out = new(StagePromotion)
		(*in).DeepCopyInto(*out)
	}
	if in.ErrorBudget != nil {
		in, out := &in.ErrorBudget, &out.ErrorBudget
		*out = new(ErrorBudget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stage.
func (in *Stage) DeepCopy() *Stage {
	if in == nil {
		return nil
	}
	out := new(Stage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageActions) DeepCopyInto(out *StageActions) {
	*out = *in
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnFailure != nil {
		in, out := &in.OnFailure, &out.OnFailure
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageActions.
func (in *StageActions) DeepCopy() *StageActions {
	if in == nil {
		return nil
	}
	out := new(StageActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageArtifactRef) DeepCopyInto(out *StageArtifactRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageArtifactRef.
func (in *StageArtifactRef) DeepCopy() *StageArtifactRef {
	if in == nil {
		return nil
	}
	out := new(StageArtifactRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageInventory) DeepCopyInto(out *StageInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageInventory.
func (in *StageInventory) DeepCopy() *StageInventory {
	if in == nil {
		return nil
	}
	out := new(StageInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StageInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageInventoryList) DeepCopyInto(out *StageInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StageInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageInventoryList.
func (in *StageInventoryList) DeepCopy() *StageInventoryList {
	if in == nil {
		return nil
	}
	out := new(StageInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StageInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageInventorySpec) DeepCopyInto(out *StageInventorySpec) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]InventoryEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageInventorySpec.
func (in *StageInventorySpec) DeepCopy() *StageInventorySpec {
	if in == nil {
		return nil
	}
	out := new(StageInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StagePromotion) DeepCopyInto(out *StagePromotion) {
	*out = *in
	if in.Soak != nil {
		in, out := &in.Soak, &out.Soak
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(PromotionAnalysis)
		(*in).DeepCopyInto(*out)
	}
	if in.FastTrack != nil {
		in, out := &in.FastTrack, &out.FastTrack
		*out = new(FastTrack)
		(*in).DeepCopyInto(*out)
	}
	if in.RestartGate != nil {
		in, out := &in.RestartGate, &out.RestartGate
		*out = new(RestartGate)
		(*in).DeepCopyInto(*out)
	}
	if in.EventGate != nil {
		in, out := &in.EventGate, &out.EventGate
		*out = new(EventGate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StagePromotion.
func (in *StagePromotion) DeepCopy() *StagePromotion {
	if in == nil {
		return nil
	}
	out := new(StagePromotion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageSet) DeepCopyInto(out *StageSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageSet.
func (in *StageSet) DeepCopy() *StageSet {
	if in == nil {
		return nil
	}
	out := new(StageSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StageSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageSetList) DeepCopyInto(out *StageSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StageSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageSetList.
func (in *StageSetList) DeepCopy() *StageSetList {
	if in == nil {
		return nil
	}
	out := new(StageSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StageSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageSetSpec) DeepCopyInto(out *StageSetSpec) {
	*out = *in
	out.Interval = in.Interval
	if in.RetryInterval != nil {
		in, out := &in.RetryInterval, &out.RetryInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.DriftDetectionInterval != nil {
		in, out := &in.DriftDetectionInterval, &out.DriftDetectionInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]meta.NamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.KubeConfig != nil {
		in, out := &in.KubeConfig, &out.KubeConfig
		*out = new(meta.KubeConfigReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Decryption != nil {
		in, out := &in.Decryption, &out.Decryption
		*out = new(Decryption)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(VersionSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Migrations != nil {
		in, out := &in.Migrations, &out.Migrations
		*out = make([]Migration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MigrationsSourceRef != nil {
		in, out := &in.MigrationsSourceRef, &out.MigrationsSourceRef
		*out = new(MigrationsSource)
		**out = **in
	}
	if in.OnRollback != nil {
		in, out := &in.OnRollback, &out.OnRollback
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpdateWindows != nil {
		in, out := &in.UpdateWindows, &out.UpdateWindows
		*out = make([]UpdateWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ErrorBudget != nil {
		in, out := &in.ErrorBudget, &out.ErrorBudget
		*out = new(ErrorBudget)
		(*in).DeepCopyInto(*out)
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]Stage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageSetSpec.
func (in *StageSetSpec) DeepCopy() *StageSetSpec {
	if in == nil {
		return nil
	}
	out := new(StageSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageSetStatus) DeepCopyInto(out *StageSetStatus) {
	*out = *in
	out.ReconcileRequestStatus = in.ReconcileRequestStatus
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAttemptedRevisions != nil {
		in, out := &in.LastAttemptedRevisions, &out.LastAttemptedRevisions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastAppliedRevisions != nil {
		in, out := &in.LastAppliedRevisions, &out.LastAppliedRevisions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]StageStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingMigrations != nil {
		in, out := &in.PendingMigrations, &out.PendingMigrations
		*out = make([]PendingMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExecutedMigrations != nil {
		in, out := &in.ExecutedMigrations, &out.ExecutedMigrations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExecutedMigrationActions != nil {
		in, out := &in.ExecutedMigrationActions, &out.ExecutedMigrationActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastAppliedSnapshot != nil {
		in, out := &in.LastAppliedSnapshot, &out.LastAppliedSnapshot
		*out = make([]StageArtifactRef, len(*in))
		copy(*out, *in)
	}
	if in.PendingUpdate != nil {
		in, out := &in.PendingUpdate, &out.PendingUpdate
		*out = new(PendingUpdate)
		(*in).DeepCopyInto(*out)
	}
	if in.BudgetFreeze != nil {
		in, out := &in.BudgetFreeze, &out.BudgetFreeze
		*out = new(BudgetFreeze)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageSetStatus.
func (in *StageSetStatus) DeepCopy() *StageSetStatus {
	if in == nil {
		return nil
	}
	out := new(StageSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageStatus) DeepCopyInto(out *StageStatus) {
	*out = *in
	if in.ExecutedActions != nil {
		in, out := &in.ExecutedActions, &out.ExecutedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExecutedVersionActions != nil {
		in, out := &in.ExecutedVersionActions, &out.ExecutedVersionActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PromotionState != nil {
		in, out := &in.PromotionState, &out.PromotionState
		*out = new(PromotionState)
		(*in).DeepCopyInto(*out)
	}
	if in.BudgetFreeze != nil {
		in, out := &in.BudgetFreeze, &out.BudgetFreeze
		*out = new(BudgetFreeze)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageStatus.
func (in *StageStatus) DeepCopy() *StageStatus {
	if in == nil {
		return nil
	}
	out := new(StageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstituteReference) DeepCopyInto(out *SubstituteReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstituteReference.
func (in *SubstituteReference) DeepCopy() *SubstituteReference {
	if in == nil {
		return nil
	}
	out := new(SubstituteReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Threshold) DeepCopyInto(out *Threshold) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(string)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Threshold.
func (in *Threshold) DeepCopy() *Threshold {
	if in == nil {
		return nil
	}
	out := new(Threshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateWindow) DeepCopyInto(out *UpdateWindow) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = (*in).DeepCopy()
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateWindow.
func (in *UpdateWindow) DeepCopy() *UpdateWindow {
	if in == nil {
		return nil
	}
	out := new(UpdateWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionSource) DeepCopyInto(out *VersionSource) {
	*out = *in
	if in.FromArtifact != nil {
		in, out := &in.FromArtifact, &out.FromArtifact
		*out = new(ArtifactVersionRef)
		**out = **in
	}
	if in.FromObject != nil {
		in, out := &in.FromObject, &out.FromObject
		*out = new(ObjectVersionRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionSource.
func (in *VersionSource) DeepCopy() *VersionSource {
	if in == nil {
		return nil
	}
	out := new(VersionSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitAction) DeepCopyInto(out *WaitAction) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(meta.NamespacedObjectKindReference)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitAction.
func (in *WaitAction) DeepCopy() *WaitAction {
	if in == nil {
		return nil
	}
	out := new(WaitAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSource) DeepCopyInto(out *WebhookSource) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(meta.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSource.
func (in *WebhookSource) DeepCopy() *WebhookSource {
	if in == nil {
		return nil
	}
	out := new(WebhookSource)
	in.DeepCopyInto(out)
	return out
}
