# SPDX-FileCopyrightText: The stageset-controller Authors
# SPDX-License-Identifier: 0BSD
apiVersion: stages.metio.wtf/v1
kind: StageSet
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  timeout: 5m
  serviceAccountName: platform-reconciler
  stages:
    - name: crds
      sourceRef:
        name: platform-crds
      prune: false
      readyChecks:
        timeout: 2m
    - name: operators
      sourceRef:
        name: operators-bundle
      path: ./manifests
      patches:
        - patch: |
            - op: replace
              path: /spec/replicas
              value: 3
          target:
            kind: Deployment
            name: ingress-nginx-controller
      readyChecks:
        timeout: 5m
        exprs:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            current: status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')
            failed: status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'False')
    - name: dashboards
      sourceRef:
        apiVersion: jaas.metio.wtf/v1
        kind: JsonnetSnippet
        name: grafana-dashboards
      readyChecks:
        timeout: 3m
    - name: webapp
      sourceRef:
        name: webapp-bundle
      actions:
        pre:
          - name: maintenance-on
            patch:
              target:
                apiVersion: networking.k8s.io/v1
                kind: Ingress
                name: webapp
                namespace: webapp
              type: json6902
              patch: |
                - op: replace
                  path: /spec/rules/0/http/paths/0/backend/service/name
                  value: maintenance-page
        post:
          - name: maintenance-off
            patch:
              target:
                apiVersion: networking.k8s.io/v1
                kind: Ingress
                name: webapp
                namespace: webapp
              type: json6902
              patch: |
                - op: replace
                  path: /spec/rules/0/http/paths/0/backend/service/name
                  value: webapp
      readyChecks:
        timeout: 10m
        checks:
          - apiVersion: apps/v1
            kind: Deployment
            name: webapp
            namespace: webapp
