baseURL = "https://stageset.metio.wtf/"
languageCode = "en-us"
title = "StageSet Controller"
disableKinds = ["taxonomy", "term", "rss"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "github-dark"
noClasses = true
