# SPDX-FileCopyrightText: The stageset-controller Authors
# SPDX-License-Identifier: 0BSD
name: Documentation
on:
  workflow_dispatch:
  schedule:
    - cron: 45 4 * * MON
  push:
    branches: [main]
    paths:
      - docs/**
  pull_request:
    paths:
      - docs/**
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3
        with:
          hugo-version: latest
          extended: true
      - run: hugo --minify --printI18nWarnings --printPathWarnings --source docs
      - name: Deploy Website
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          force_orphan: true
          cname: stageset.projects.metio.wtf
